# Generated by Django 5.2.12 on 2026-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Pending"), (1, "Accepted"), (2, "Rejected")],
                default=0,
            ),
        ),
    ]
